### ISSUE TITLE
problem with Julia 1.6.7

### ISSUE THREAD

**Issue by ThomasBreuer** [jmichel7/Chevie.jl#6]
When trying to load the package into Julia 1.6.7, I get the error message `ERROR: LoadError: UndefVarError: exactdiv not defined`.
The point seems to be that `LinearAlgebra.exactdiv` is not defined in this version of Julia.
With Julia 1.7.2 or newer, I do not get this problem.

**Comment by jmichel7** [comment]
As I said in you pull request did not see your message. Bumped the julia dependency to  1.8 because of allequal

**Comment by ThomasBreuer** [comment]
Thanks!
